/* ------------------------------------------------------------------ *
 *  The 100 questions of the 2020 PhilPapers Survey, turned into a
 *  personality test.  Source question wording follows the published
 *  survey design (Bourget & Chalmers, "Philosophers on Philosophy:
 *  The 2020 PhilPapers Survey").
 *
 *  Each question is assigned to one of ten thematic categories so the
 *  results can be drawn as a colour-banded profile diagram (see the
 *  example SVG in /example).
 *
 *  `detail` is a plain-language gloss added for this quiz: it explains
 *  the jargon and lays out what each option commits you to, so newcomers
 *  aren't lost and old hands get a memory-jog.  It is NOT part of the
 *  original survey wording.  Detail strings may use "\n" line breaks and
 *  "• " bullets; the .qdetail style renders them via white-space: pre-line.
 * ------------------------------------------------------------------ */

/* Category metadata — colours echo the soft, banded palette of the
 * example diagram (rounded cards, pale fill, saturated accent). */
window.PPT_CATEGORIES = [
  { key: 'meta', name: 'Metaphysics & religion',        fill: '#EEEDFE', stroke: '#534AB7', title: '#3C3489', text: '#534AB7' },
  { key: 'mind', name: 'Mind & cognition',              fill: '#E1F5EE', stroke: '#0F6E56', title: '#085041', text: '#0F6E56' },
  { key: 'consc', name: 'Consciousness, self & AI',     fill: '#E0F2F4', stroke: '#0E7490', title: '#0B5566', text: '#0E7490' },
  { key: 'epis', name: 'Epistemology',                  fill: '#E6F1FB', stroke: '#185FA5', title: '#0C447C', text: '#185FA5' },
  { key: 'ethm', name: 'Ethics & meta-ethics',          fill: '#FAECE7', stroke: '#993C1D', title: '#712B13', text: '#993C1D' },
  { key: 'appl', name: 'Applied ethics & the good life', fill: '#FBE9EF', stroke: '#A12B53', title: '#781E3D', text: '#A12B53' },
  { key: 'pol',  name: 'Politics, society & identity',  fill: '#FAEEDA', stroke: '#854F0B', title: '#633806', text: '#854F0B' },
  { key: 'lang', name: 'Language, logic & mathematics',  fill: '#F3E9FB', stroke: '#6B2FA1', title: '#4E2178', text: '#6B2FA1' },
  { key: 'sci',  name: 'Science & nature',              fill: '#EAF3E2', stroke: '#4D7C0F', title: '#3A5E0B', text: '#4D7C0F' },
  { key: 'hist', name: 'History & methods',             fill: '#EEEEEC', stroke: '#57534E', title: '#3D3D3A', text: '#57534E' }
];

/* The questions.  `id` matches the survey numbering above; `cat` is the
 * category key; `topic` is the short label used on result cards; `q` is
 * the full prompt; `detail` is a plain-language explainer; `opts` are the
 * answer options; `multi:true` marks the two list-style questions
 * (philosophical method, other minds); `combo:true` marks questions where
 * the survey shows a single position is often combined with others
 * (normative ethics, aim of philosophy, gender, race) — both let you pick
 * several options. `surveyOpts` (on Q37) records how many of the listed
 * options have survey comparison data. `optNotes` gives a short gloss
 * shown under each option label; it is used on the jargon-heavy
 * multi-option questions, in `opts` order. When a question has optNotes,
 * the per-option bullets are dropped from `detail`, which keeps only the
 * framing question and any commentary. */
window.PPT_QUESTIONS = [
  { id: 1,  cat: 'epis', topic: 'A priori knowledge',      q: 'A priori knowledge: is there any?',               opts: ['Yes', 'No'],
    detail: "A priori knowledge is knowledge you can have independently of experience — justified by reason or reflection alone, like knowing that all bachelors are unmarried or that 2 + 2 = 4.\n\nIs there any such knowledge, or does everything we know ultimately rest on observation?" },
  { id: 2,  cat: 'lang', topic: 'Abstract objects',        q: 'Abstract objects: Platonism or nominalism?',      opts: ['Platonism', 'Nominalism'],
    detail: "Do abstract things like numbers, sets, and properties really exist?\n\n• Platonism: yes — they exist independently of us, outside space and time.\n• Nominalism: no — only concrete things exist, and talk of 'abstract objects' is a useful fiction or just words." },
  { id: 3,  cat: 'appl', topic: 'Aesthetic value',         q: 'Aesthetic value: objective or subjective?',       opts: ['Objective', 'Subjective'],
    detail: "When something is beautiful, where does the beauty lie?\n\n• Objective: a real feature of the thing, the way its mass is.\n• Subjective: it exists only in the response of the beholder, so there is nothing to be right or wrong about." },
  { id: 4,  cat: 'epis', topic: 'Analytic–synthetic',      q: 'Analytic–synthetic distinction: is there one?',   opts: ['Yes', 'No'],
    detail: "Analytic truths are supposed to be true by meaning alone ('all bachelors are unmarried'); synthetic truths depend on how the world is ('it is raining').\n\nQuine famously attacked the idea that there is a clean line between the two. Is there a real distinction?" },
  { id: 5,  cat: 'epis', topic: 'Epistemic justification', q: 'Epistemic justification: internalism or externalism?', opts: ['Internalism', 'Externalism'],
    detail: "What makes a belief justified?\n\n• Internalism: only things you can access from the inside — your other beliefs and experiences.\n• Externalism: facts outside your awareness can count too, such as whether the belief was produced by a reliable process." },
  { id: 6,  cat: 'epis', topic: 'External world',          q: 'External world: idealism, skepticism, or non-skeptical realism?', opts: ['Idealism', 'Skepticism', 'Non-skeptical realism'],
    detail: "Do ordinary objects exist independently of minds, and can we know it?\n\n• Non-skeptical realism: yes and yes.\n• Skepticism: maybe they do, but we can't really know.\n• Idealism: reality is ultimately mental, so there is no mind-independent external world in the first place." },
  { id: 7,  cat: 'meta', topic: 'Free will',               q: 'Free will: compatibilism, libertarianism, or no free will?', opts: ['Compatibilism', 'Libertarianism', 'No free will'],
    detail: "Can we be free if every event is caused by prior events?\n\n• Compatibilism: yes — freedom is compatible with determinism.\n• Libertarianism: we really are free, so determinism must be false.\n• No free will (hard determinism): determinism holds and genuine free will is an illusion." },
  { id: 8,  cat: 'meta', topic: 'God',                     q: 'God: theism or atheism?',                         opts: ['Theism', 'Atheism'],
    detail: "• Theism: at least one god exists.\n• Atheism: there is no god.\n\n(The survey's binary leaves agnostics to mark themselves undecided.)" },
  { id: 9,  cat: 'epis', topic: 'Knowledge',               q: 'Knowledge: empiricism or rationalism?',           opts: ['Empiricism', 'Rationalism'],
    detail: "Where does substantive knowledge ultimately come from?\n\n• Empiricism: from sense experience (Locke, Hume).\n• Rationalism: reason on its own can deliver knowledge of the world (Descartes, Leibniz)." },
  { id: 10, cat: 'epis', topic: 'Knowledge claims',        q: 'Knowledge claims: contextualism, relativism, or invariantism?', opts: ['Contextualism', 'Relativism', 'Invariantism'],
    detail: "Does the word 'knows' set a fixed bar?\n\n• Invariantism: yes, the standard for knowing is the same everywhere.\n• Contextualism: how much you need in order to count as 'knowing' shifts with the conversation.\n• Relativism: whether a knowledge claim is true depends on who is assessing it." },
  { id: 11, cat: 'sci',  topic: 'Laws of nature',          q: 'Laws of nature: Humean or non-Humean?',           opts: ['Humean', 'Non-Humean'],
    detail: "What are the laws of nature?\n\n• Humean: just compact summaries of the regular patterns that happen to hold.\n• Non-Humean: they reflect real necessities or powers in nature that actually make events happen." },
  { id: 12, cat: 'lang', topic: 'Logic',                   q: 'Logic: classical or non-classical?',              opts: ['Classical', 'Non-classical'],
    detail: "Which is the correct logic?\n\n• Classical: assumes principles like bivalence (every statement is true or false) and excluded middle.\n• Non-classical: intuitionist, paraconsistent, or many-valued logics, which drop some of these." },
  { id: 13, cat: 'mind', topic: 'Mental content',          q: 'Mental content: internalism or externalism?',     opts: ['Internalism', 'Externalism'],
    detail: "Is what your thoughts are about fixed entirely by what's inside your head, or partly by your environment and history?\n\n• Internalism: content is fixed entirely by what's inside your head.\n• Externalism: it's fixed partly by your environment and history.\n\nPutnam's Twin Earth case suggests 'water' means different things for molecule-identical twins in different worlds." },
  { id: 14, cat: 'ethm', topic: 'Meta-ethics',             q: 'Meta-ethics: moral realism or moral anti-realism?', opts: ['Moral realism', 'Moral anti-realism'],
    detail: "Are there objective moral facts — is 'torturing babies for fun is wrong' true independently of what anyone thinks?\n\n• Moral realism: yes, there are mind-independent moral facts.\n• Moral anti-realism: morality has no mind-independent truth, being instead attitude, convention, or systematic error." },
  { id: 15, cat: 'hist', topic: 'Metaphilosophy',          q: 'Metaphilosophy: naturalism or non-naturalism?',   opts: ['Naturalism', 'Non-naturalism'],
    detail: "Should philosophy be continuous with the natural sciences?\n\n• Naturalism: yes — philosophy is answerable to empirical findings and methods.\n• Non-naturalism: it has its own distinct, non-empirical subject matter and methods." },
  { id: 16, cat: 'mind', topic: 'Mind',                    q: 'Mind: physicalism or non-physicalism?',           opts: ['Physicalism', 'Non-physicalism'],
    detail: "Is the mind ultimately physical?\n\n• Physicalism: nothing over and above the brain and body.\n• Non-physicalism: it involves something non-physical, like irreducible consciousness or a soul." },
  { id: 17, cat: 'ethm', topic: 'Moral judgment',          q: 'Moral judgment: cognitivism or non-cognitivism?', opts: ['Cognitivism', 'Non-cognitivism'],
    detail: "When you say 'stealing is wrong', what are you doing?\n\n• Cognitivism: stating a belief that can be true or false.\n• Non-cognitivism: expressing an attitude or feeling, more like 'boo, stealing!'." },
  { id: 18, cat: 'ethm', topic: 'Moral motivation',        q: 'Moral motivation: internalism or externalism?',   opts: ['Internalism', 'Externalism'],
    detail: "If you sincerely judge an act to be wrong, are you necessarily at least somewhat motivated not to do it?\n\n• Internalism: yes — the judgment necessarily brings at least some motivation.\n• Externalism: no — someone can judge it wrong and feel no pull whatsoever." },
  { id: 19, cat: 'lang', topic: "Newcomb's problem",       q: "Newcomb's problem: one box or two boxes?",        opts: ['One box', 'Two boxes'],
    detail: "A reliable predictor has already put $1M in box B only if it predicted you'd take B alone; box A always holds $1k.\n\n• Two boxes: the money is already there — take both (dominance reasoning).\n• One box: take B alone — one-boxers tend to walk away rich.\n\nIt pits two theories of rational decision against each other." },
  { id: 20, cat: 'ethm', topic: 'Normative ethics',        q: 'Normative ethics: deontology, consequentialism, or virtue ethics?', opts: ['Deontology', 'Consequentialism', 'Virtue ethics'], combo: true,
    detail: "Three families of ethical theory.\n\n• Consequentialism: rightness depends only on outcomes (maximize the good).\n• Deontology: some acts are required or forbidden by duties or rules whatever the outcome (Kant).\n• Virtue ethics: focus on character — what a virtuous person would do (Aristotle).\n\nMany philosophers hold a combination — about one in six in the survey did — so pick one or several." },
  { id: 21, cat: 'mind', topic: 'Perceptual experience',   q: 'Perceptual experience: disjunctivism, qualia theory, representationalism, or sense-datum theory?', opts: ['Disjunctivism', 'Qualia theory', 'Representationalism', 'Sense-datum theory'],
    optNotes: ['seeing and hallucinating are different states', 'intrinsic felt qualities', 'the experience represents the world', "you're directly aware of a mental object"],
    detail: "What is going on when you see a red tomato?" },
  { id: 22, cat: 'consc', topic: 'Personal identity',      q: 'Personal identity: biological, psychological, or further-fact view?', opts: ['Biological view', 'Psychological view', 'Further-fact view'],
    detail: "What makes you the same person over time?\n\n• Biological view: continuity of your living organism.\n• Psychological view: continuity of memories, personality, and consciousness (Locke).\n• Further-fact view: identity is a deep extra fact beyond both, often tied to a soul or simple self." },
  { id: 23, cat: 'pol',  topic: 'Political philosophy',    q: 'Political philosophy: communitarianism, egalitarianism, or libertarianism?', opts: ['Communitarianism', 'Egalitarianism', 'Libertarianism'],
    detail: "Three broad approaches to political philosophy.\n\n• Libertarianism: liberty and property rights come first, with minimal state interference.\n• Egalitarianism: justice requires actively reducing inequality.\n• Communitarianism: individuals are shaped by their communities, so shared values and the common good matter, against abstract individualism." },
  { id: 24, cat: 'lang', topic: 'Proper names',            q: 'Proper names: Fregean or Millian?',               opts: ['Fregean', 'Millian'],
    detail: "What does a name like 'Aristotle' contribute to meaning?\n\n• Millian: just its bearer — the man himself.\n• Fregean: also a 'sense', a mode of presentation, which explains why 'Hesperus is Phosphorus' is informative even though both name Venus." },
  { id: 25, cat: 'sci',  topic: 'Science',                 q: 'Science: scientific realism or scientific anti-realism?', opts: ['Scientific realism', 'Scientific anti-realism'],
    detail: "Do our best scientific theories give a roughly true description of unobservable reality — electrons, fields, quarks?\n\n• Scientific realism: yes — they're roughly true about those hidden entities.\n• Scientific anti-realism: they're just useful instruments for predicting observations, without committing us to those entities." },
  { id: 26, cat: 'consc', topic: 'Teletransporter',        q: 'Teletransporter (new matter): survival or death?', opts: ['Survival', 'Death'],
    detail: "A machine scans and destroys you here, then builds a perfect atom-for-atom copy on Mars out of new matter.\n\n• Survival: that person on Mars wakes up as you.\n• Death: you died and a mere replica took your place.\n\nParfit's case probes what we really care about in surviving." },
  { id: 27, cat: 'meta', topic: 'Time',                    q: 'Time: A-theory or B-theory?',                     opts: ['A-theory', 'B-theory'],
    detail: "Is the passage of time real?\n\n• A-theory: yes — there is an objective 'now' that flows, and past, present, and future differ deeply.\n• B-theory: all times are equally real, 'now' is like 'here' (just where the speaker is), and the flow of time is a feature of our perspective, not of reality." },
  { id: 28, cat: 'appl', topic: 'Trolley problem',         q: 'Trolley problem (five ahead, one on a side track, turning requires switching): switch or don’t switch?', opts: ['Switch', "Don't switch"],
    detail: "A runaway trolley will kill five people ahead. You can pull a lever to divert it onto a side track where it kills one person instead.\n\n• Switch: flip the lever, killing one to save five.\n• Don't switch: do not intervene.\n\nThe classic test of consequentialist versus deontological intuitions." },
  { id: 29, cat: 'lang', topic: 'Truth',                   q: 'Truth: correspondence, deflationary, or epistemic?', opts: ['Correspondence', 'Deflationary', 'Epistemic'],
    detail: "What is truth?\n\n• Correspondence: a belief is true when it matches reality.\n• Deflationary: saying 'p is true' adds nothing to asserting 'p' — truth is not a deep property.\n• Epistemic: truth is tied to what we would be justified in believing, ideally (say, at the end of inquiry)." },
  { id: 30, cat: 'consc', topic: 'Zombies',                q: 'Zombies: inconceivable, conceivable but not metaphysically possible, or metaphysically possible?', opts: ['Inconceivable', 'Conceivable but not metaphysically possible', 'Metaphysically possible'],
    detail: "A 'philosophical zombie' is physically identical to you but has no inner experience at all — dark inside. If such a being is genuinely possible, consciousness can't be purely physical.\n\n• Inconceivable: we can't even coherently imagine one.\n• Conceivable but not metaphysically possible: imaginable, yet impossible in reality.\n• Metaphysically possible: genuinely possible — and so consciousness isn't purely physical.\n\nIt anchors Chalmers' anti-physicalist argument." },
  { id: 31, cat: 'hist', topic: 'Aim of philosophy',       q: 'Aim of philosophy (most important?): truth/knowledge, understanding, wisdom, happiness, or goodness/justice?', opts: ['Truth/knowledge', 'Understanding', 'Wisdom', 'Happiness', 'Goodness/justice'], combo: true,
    detail: "What should philosophy ultimately be for?\n\n• Truth/knowledge: accurate theory.\n• Understanding: deeper understanding.\n• Wisdom: practical wisdom for living.\n• Happiness: human flourishing.\n• Goodness/justice: a better and more just world.\n\nIn the survey this allowed several answers at once (most picked more than one), so select all you value." },
  { id: 32, cat: 'appl', topic: 'Eating animals',          q: 'Eating animals and animal products (ordinarily permissible?): omnivorism, vegetarianism, or veganism?', opts: ['Omnivorism (yes and yes)', 'Vegetarianism (no and yes)', 'Veganism (no and no)'],
    detail: "Is it ordinarily permissible to eat (a) animals and (b) animal products like eggs and dairy?\n\n• Omnivorism: yes and yes.\n• Vegetarianism: no meat, but products are OK.\n• Veganism: neither." },
  { id: 33, cat: 'appl', topic: 'Experience machine',      q: 'Experience machine: would you enter?',             opts: ['Yes', 'No'],
    detail: "Nozick's machine would give you a lifetime of perfectly convincing, pleasant experiences — but it's all simulated and you'd never know. Plug in for good?\n\nRefusing suggests we value actually doing and being things, not just the experience of them — a challenge to hedonism." },
  { id: 34, cat: 'appl', topic: 'Footbridge',              q: 'Footbridge (pushing a man off a bridge will save five below): push or don’t push?', opts: ['Push', "Don't push"],
    detail: "Like the trolley case, but now the only way to stop the trolley killing five is to push a large stranger off a footbridge into its path, killing him.\n\nMost people who would flip a switch won't push — even though the arithmetic (one death, five saved) is the same. Why the difference?" },
  { id: 35, cat: 'pol',  topic: 'Gender',                  q: 'Gender: biological, psychological, social, or unreal?', opts: ['Biological', 'Psychological', 'Social', 'Unreal'], combo: true,
    detail: "What is gender most fundamentally?\n\n• Biological: grounded in sex and biology.\n• Psychological: grounded in identity or self-understanding.\n• Social: constituted by social roles, norms, and position.\n• Unreal: not a genuine category at all.\n\nCombinations were widely endorsed in the survey (e.g. psychological-and-social), so pick one or several." },
  { id: 36, cat: 'appl', topic: 'Meaning of life',         q: 'Meaning of life: subjective, objective, or nonexistent?', opts: ['Subjective', 'Objective', 'Nonexistent'],
    detail: "Does life have meaning, and if so where from?\n\n• Subjective: meaning is whatever you find or make matter to you.\n• Objective: some things are genuinely meaningful regardless of your attitudes.\n• Nonexistent: life has no meaning in any deep sense." },
  { id: 37, cat: 'hist', topic: 'Philosophical method',    q: 'Philosophical method (most useful?): conceptual analysis, conceptual engineering, empirical, experimental, formal, intuition-based, linguistic, or others?', opts: ['Conceptual analysis', 'Conceptual engineering', 'Empirical philosophy', 'Experimental philosophy', 'Formal philosophy', 'Intuition-based philosophy', 'Linguistic philosophy', 'Phenomenology', 'Historical / textual', 'Pragmatist', 'Genealogical', 'Hermeneutic', 'Critical theory', 'Reflective equilibrium'], multi: true, surveyOpts: 7,
    optNotes: ['unpacking our concepts', 'improving our concepts', 'drawing on science', "surveying people's intuitions", 'logic and mathematics', 'appeals to what seems obvious', 'close attention to language', 'describing lived experience', 'reading the canon closely', 'judging ideas by their practical effects', 'tracing how concepts came to be', 'the art of interpretation', 'philosophy aimed at social critique', 'balancing principles against intuitions'],
    detail: "Which methods are most useful for doing philosophy? (Select any that apply.)\n\nThe survey offered the first seven. Respondents protested that these skewed analytic, and the most common write-ins were phenomenology, historical, pragmatist, and genealogical methods — added here, along with hermeneutics, critical theory, and reflective equilibrium.\n\n(Comparison figures exist only for the original seven.)" },
  { id: 38, cat: 'hist', topic: 'Philosophical progress',  q: 'Philosophical progress (how much is there?): none, a little, or a lot?', opts: ['None', 'A little', 'A lot'],
    detail: "How much genuine progress has philosophy made over its history?\n\nUnlike the sciences, it is often accused of circling the same questions for millennia. How much has actually been settled or advanced?" },
  { id: 39, cat: 'pol',  topic: 'Race',                    q: 'Race: biological, social, or unreal?',             opts: ['Biological', 'Social', 'Unreal'], combo: true,
    detail: "What is race?\n\n• Biological: a real biological grouping.\n• Social: a real category, but constituted by social practices and history rather than biology.\n• Unreal: not a genuine kind at all — a category we should stop treating as real.\n\nCombinations (e.g. biological-and-social, or social-and-unreal) were common in the survey, so pick one or several." },
  { id: 40, cat: 'lang', topic: 'Vagueness',               q: 'Vagueness: epistemic, metaphysical, or semantic?', opts: ['Epistemic', 'Metaphysical', 'Semantic'],
    detail: "Why is it indeterminate exactly how many grains make a 'heap'?\n\n• Epistemic: there is a sharp cut-off, we just can't know where.\n• Semantic: our words are loose and never fixed a precise boundary.\n• Metaphysical: the world itself is genuinely fuzzy." },
  { id: 41, cat: 'appl', topic: 'Abortion',                q: 'Abortion (first trimester, no special circumstances): permissible or impermissible?', opts: ['Permissible', 'Impermissible'],
    detail: "Setting aside special circumstances, is abortion in the first trimester morally permissible?\n\nThe answer turns largely on the moral status of the early fetus and the weight given to bodily autonomy." },
  { id: 42, cat: 'appl', topic: 'Aesthetic experience',    q: 'Aesthetic experience: perception, pleasure, or sui generis?', opts: ['Perception', 'Pleasure', 'Sui generis'],
    detail: "What kind of mental state is aesthetic experience?\n\n• Perception: a way of perceiving.\n• Pleasure: a form of pleasure.\n• Sui generis: its own irreducible kind of experience, not reducible to either." },
  { id: 43, cat: 'epis', topic: 'Analysis of knowledge',   q: 'Analysis of knowledge: justified true belief, other analysis, or no analysis?', opts: ['Justified true belief', 'Other analysis', 'No analysis'],
    detail: "Is knowledge just justified true belief (JTB)? Gettier cases — true, justified beliefs that seem lucky rather than knowledge — broke that classic analysis.\n\n• Justified true belief: the classic analysis is basically right.\n• Other analysis: a different analysis can fix it.\n• No analysis: knowledge resists analysis altogether." },
  { id: 44, cat: 'meta', topic: 'Arguments for theism',    q: 'Arguments for theism (strongest?): cosmological, design, ontological, pragmatic, or moral?', opts: ['Cosmological', 'Design', 'Ontological', 'Pragmatic', 'Moral'],
    optNotes: ['why is there anything; a first cause', 'the universe looks fine-tuned', 'existence follows from the concept of God', 'belief pays off (Pascal, James)', 'morality needs a divine ground'],
    detail: "Which is the strongest argument for God's existence?" },
  { id: 45, cat: 'epis', topic: 'Belief or credence',      q: 'Belief or credence (more fundamental?): belief, credence, or neither?', opts: ['Belief', 'Credence', 'Neither'],
    detail: "Which is the more fundamental attitude?\n\n• Belief: flat-out belief — you simply believe it.\n• Credence: a degree of confidence, say 70%.\n• Neither: neither is basic, with both resting on something else." },
  { id: 46, cat: 'appl', topic: 'Capital punishment',      q: 'Capital punishment: permissible or impermissible?', opts: ['Permissible', 'Impermissible'],
    detail: "Is it ever morally permissible for the state to execute criminals?\n\nIt weighs retribution and deterrence against the wrongness of killing and the risk of executing the innocent." },
  { id: 47, cat: 'meta', topic: 'Causation',               q: 'Causation: counterfactual/difference-making, process/production, primitive, or nonexistent?', opts: ['Counterfactual / difference-making', 'Process / production', 'Primitive', 'Nonexistent'],
    optNotes: ["had A not happened, B wouldn't have", 'a physical process or transfer links them', "basic; can't be analyzed further", 'a fiction projected onto mere regularities'],
    detail: "What is it for A to cause B?" },
  { id: 48, cat: 'consc', topic: 'Chinese room',           q: 'Chinese room: does the system understand?',        opts: ['Understands', "Doesn't understand"],
    detail: "Searle imagines a person who knows no Chinese shuffling symbols by a rulebook and producing fluent Chinese replies — without understanding a word.\n\nIf the whole system passes as a Chinese speaker, does it genuinely understand, or merely simulate understanding? An objection to 'strong AI'." },
  { id: 49, cat: 'mind', topic: 'Concepts',                q: 'Concepts: nativism or empiricism?',                opts: ['Nativism', 'Empiricism'],
    detail: "Where do our basic concepts come from?\n\n• Nativism: they're innate, part of the mind's native equipment.\n• Empiricism: they're all acquired from experience, with the mind starting as a blank slate." },
  { id: 50, cat: 'consc', topic: 'Consciousness',          q: 'Consciousness: dualism, eliminativism, functionalism, identity theory, or panpsychism?', opts: ['Dualism', 'Eliminativism', 'Functionalism', 'Identity theory', 'Panpsychism'],
    optNotes: ['non-physical, over and above the brain', "as we conceive it, doesn't really exist", 'defined by its causal role', 'identical to brain states', 'fundamental, and pervades all matter'],
    detail: "What is consciousness?" },
  { id: 51, cat: 'lang', topic: 'Continuum hypothesis',    q: 'Continuum hypothesis (determinate truth-value?): determinate or indeterminate?', opts: ['Determinate', 'Indeterminate'],
    detail: "Cantor's continuum hypothesis says there is no size of infinity strictly between the integers and the real numbers. It is provably neither provable nor refutable from standard set theory.\n\n• Determinate: it still has a determinate truth-value we just can't reach.\n• Indeterminate: there is no fact of the matter." },
  { id: 52, cat: 'meta', topic: 'Cosmological fine-tuning', q: 'Cosmological fine-tuning (what explains it?): design, multiverse, brute fact, or no fine-tuning?', opts: ['Design', 'Multiverse', 'Brute fact', 'No fine-tuning'],
    detail: "The constants of physics look improbably fine-tuned for life. Why?\n\n• Design: something tuned them.\n• Multiverse: countless universes exist and we find ourselves in a hospitable one.\n• Brute fact: it just is, no explanation needed.\n• No fine-tuning: the premise is mistaken." },
  { id: 53, cat: 'appl', topic: 'Environmental ethics',    q: 'Environmental ethics: anthropocentric or non-anthropocentric?', opts: ['Anthropocentric', 'Non-anthropocentric'],
    detail: "Does nature matter only insofar as it affects humans?\n\n• Anthropocentric: yes — nature's value is its value to humans.\n• Non-anthropocentric: ecosystems, species, or non-human life have value in their own right." },
  { id: 54, cat: 'epis', topic: 'Justification (theory)',  q: 'Epistemic justification: coherentism, infinitism, nonreliabilist foundationalism, or reliabilism?', opts: ['Coherentism', 'Infinitism', 'Nonreliabilist foundationalism', 'Reliabilism'],
    optNotes: ['beliefs support each other in a web', 'an endless chain of reasons', 'rests on basic, self-justifying beliefs', 'produced by a reliable process'],
    detail: "How is justification structured?" },
  { id: 55, cat: 'mind', topic: 'Extended mind',           q: 'Extended mind: yes or no?',                        opts: ['Yes', 'No'],
    detail: "Clark and Chalmers argue your mind can extend beyond your skull — a notebook you rely on could be part of your memory just as your neurons are.\n\nDoes cognition literally extend into tools and environment, or does the mind stop at the skin?" },
  { id: 56, cat: 'lang', topic: 'Foundations of maths',    q: 'Foundations of mathematics: intuitionism/constructivism, formalism, logicism, structuralism, or set-theoretic?', opts: ['Intuitionism / constructivism', 'Formalism', 'Logicism', 'Structuralism', 'Set-theoretic'],
    optNotes: ['a mental construction', 'manipulating symbols by rules', 'it reduces to logic', 'about structures, not objects', 'set theory is the foundation'],
    detail: "What grounds mathematics?" },
  { id: 57, cat: 'pol',  topic: 'Gender categories',       q: 'Gender categories: preserve, revise, or eliminate?', opts: ['Preserve', 'Revise', 'Eliminate'],
    detail: "Going forward, what should we do with our gender concepts?\n\n• Preserve: keep them as they are.\n• Revise: reform them.\n• Eliminate: get rid of gender categories altogether." },
  { id: 58, cat: 'mind', topic: 'Grounds of intentionality', q: 'Grounds of intentionality: causal/teleological, inferential, interpretational, phenomenal, or primitive?', opts: ['Causal / teleological', 'Inferential', 'Interpretational', 'Phenomenal', 'Primitive'],
    optNotes: ['causal links or biological function', 'its role in reasoning', 'what a best interpreter would ascribe', 'consciousness grounds it', 'aboutness is basic and unexplained'],
    detail: "What makes a mental state about something (its 'intentionality')?" },
  { id: 59, cat: 'consc', topic: 'Hard problem',           q: 'Hard problem of consciousness: is there one?',     opts: ['Yes', 'No'],
    detail: "Even after we explain every brain function, a question seems to linger: why is any of it accompanied by subjective experience — why isn't it all dark inside?\n\nIs that 'hard problem' a real, distinct problem (Chalmers), or a confusion that dissolves on analysis?" },
  { id: 60, cat: 'appl', topic: 'Genetic engineering',     q: 'Human genetic engineering: permissible or impermissible?', opts: ['Permissible', 'Impermissible'],
    detail: "Is it morally permissible to genetically modify humans — editing embryos, selecting traits?\n\nIt weighs the benefits, such as curing disease, against risks, questions of consent, and worries about 'playing God'." },
  { id: 61, cat: 'hist', topic: 'Hume',                    q: 'Hume (what is his view?): skeptic or naturalist?', opts: ['Skeptic', 'Naturalist'],
    detail: "Interpreting Hume:\n\n• Skeptic: fundamentally undermining our claims to know causation, the self, and the external world.\n• Naturalist: despite those doubts, explaining how human nature unavoidably leads us to such beliefs anyway." },
  { id: 62, cat: 'appl', topic: 'Immortality',             q: 'Immortality: would you choose it?',                opts: ['Yes', 'No'],
    detail: "If you could live forever, would you?\n\nSome argue an endless life would eventually grow tedious and drain meaning (Bernard Williams); others that there is always more worth doing and experiencing." },
  { id: 63, cat: 'meta', topic: 'Interlevel metaphysics',  q: 'Interlevel metaphysics (most useful?): grounding, identity, realization, or supervenience?', opts: ['Grounding', 'Identity', 'Realization', 'Supervenience'],
    optNotes: ['one holds in virtue of another', "they're the same", 'the higher is implemented by the lower', 'no change in one without a change in the other'],
    detail: "How do higher-level facts relate to lower-level ones — mind to brain, social to physical? Which relation is most useful?" },
  { id: 64, cat: 'hist', topic: 'Kant',                    q: 'Kant (what is his view?): one world or two worlds?', opts: ['One world', 'Two worlds'],
    detail: "Interpreting Kant's split between appearances (phenomena) and things-in-themselves (noumena):\n\n• Two worlds: these are two distinct worlds.\n• One world: two aspects of, or standpoints on, one and the same world." },
  { id: 65, cat: 'pol',  topic: 'Law',                     q: 'Law: legal positivism or legal non-positivism?',  opts: ['Legal positivism', 'Legal non-positivism'],
    detail: "What makes something law?\n\n• Legal positivism: law is whatever is laid down by the right social and institutional sources — its content and its morality are separate questions.\n• Legal non-positivism: there is a necessary connection between law and morality, so a grossly unjust 'law' may not be law at all." },
  { id: 66, cat: 'meta', topic: 'Material composition',    q: 'Material composition: nihilism, restrictivism, or universalism?', opts: ['Nihilism', 'Restrictivism', 'Universalism'],
    detail: "When do parts compose a further whole?\n\n• Universalism: always — any objects whatever compose something, even 'your nose plus the Moon'.\n• Nihilism: never — there are only simples, no composite objects.\n• Restrictivism: only sometimes, under special conditions (the commonsense middle ground)." },
  { id: 67, cat: 'meta', topic: 'Metaontology',            q: 'Metaontology: heavyweight realism, deflationary realism, or anti-realism?', opts: ['Heavyweight realism', 'Deflationary realism', 'Anti-realism'],
    detail: "When we ask 'do numbers, tables, or properties exist?', how deep is the question?\n\n• Heavyweight realism: it's a substantive question about reality.\n• Deflationary realism: the answers are almost trivial, settled by ordinary usage.\n• Anti-realism: such existence questions are defective or merely verbal." },
  { id: 68, cat: 'hist', topic: 'History of philosophy',   q: 'Method in the history of philosophy: analytic/rational reconstruction or contextual/historicist?', opts: ['Analytic / rational reconstruction', 'Contextual / historicist'],
    detail: "How should we read past philosophers?\n\n• Analytic / rational reconstruction: mine their arguments for what is true and defensible by today's standards.\n• Contextual / historicist: understand them on their own terms, in their historical setting, before judging." },
  { id: 69, cat: 'pol',  topic: 'Political method',        q: 'Method in political philosophy: ideal theory or non-ideal theory?', opts: ['Ideal theory', 'Non-ideal theory'],
    detail: "Where should political philosophy start?\n\n• Ideal theory: first work out the perfectly just society and use it as a target (e.g. Rawls).\n• Non-ideal theory: start from actual injustices and feasible improvements here and now." },
  { id: 70, cat: 'consc', topic: 'Mind uploading',         q: 'Mind uploading (brain replaced by digital emulation): survival or death?', opts: ['Survival', 'Death'],
    detail: "Your brain is replaced — gradually or all at once — by a digital emulation that behaves exactly like you.\n\n• Survival: you survive as the upload.\n• Death: the original you dies while a digital copy carries on.\n\nA cousin of the teletransporter case." },
  { id: 71, cat: 'ethm', topic: 'Moral principles',        q: 'Moral principles: moral generalism or moral particularism?', opts: ['Moral generalism', 'Moral particularism'],
    detail: "Does morality rest on general principles?\n\n• Moral generalism: yes — principles hold across cases.\n• Moral particularism: what's right depends on the particulars of each situation, with no exceptionless rules (Dancy)." },
  { id: 72, cat: 'ethm', topic: 'Morality (nature of)',    q: 'Morality: non-naturalism, naturalist realism, constructivism, expressivism, or error theory?', opts: ['Non-naturalism', 'Naturalist realism', 'Constructivism', 'Expressivism', 'Error theory'],
    optNotes: ['real moral facts, but not natural ones', 'moral facts just are natural facts', 'truths constructed from our standpoints', 'moral talk expresses attitudes, not facts', 'moral claims aim at facts, but all are false'],
    detail: "Five metaethical pictures." },
  { id: 73, cat: 'ethm', topic: 'Normative concepts',      q: 'Normative concepts (most fundamental?): fit, ought, reason, or value?', opts: ['Fit', 'Ought', 'Reason', 'Value'],
    detail: "Which normative notion is most fundamental, with the others defined from it?\n\n• Fit: the fittingness of an attitude to its object.\n• Ought: what one should do.\n• Reason: a consideration that counts in favor.\n• Value: goodness." },
  { id: 74, cat: 'consc', topic: 'Other minds',            q: 'Other minds (which groups have conscious members?): adult humans, cats, fish, flies, worms, plants, particles, newborns, current AI, future AI?', opts: ['Adult humans', 'Cats', 'Fish', 'Flies', 'Worms', 'Plants', 'Particles', 'Newborn babies', 'Current AI systems', 'Future AI systems'], multi: true,
    detail: "Which of these groups have conscious members? (Select any that apply.)\n\nFrom adult humans down through cats, fish, flies, worms, plants, fundamental particles, newborn babies, and on to current and future AI systems — where do you draw the line on who has an inner life?" },
  { id: 75, cat: 'ethm', topic: 'Ought implies can',       q: 'Ought implies can: yes or no?',                    opts: ['Yes', 'No'],
    detail: "Kant's principle: if you morally ought to do something, then you must be able to do it — you can't be obligated to do the impossible.\n\nIs that true, or can there be obligations one simply cannot fulfill, as in a genuine moral dilemma?" },
  { id: 76, cat: 'hist', topic: 'Philosophical knowledge', q: 'Philosophical knowledge (how much is there?): none, a little, or a lot?', opts: ['None', 'A little', 'A lot'],
    detail: "How much genuine knowledge — as opposed to mere opinion — has philosophy actually produced?\n\nRelated to but distinct from progress: you might think much is known yet little has advanced lately, or the reverse." },
  { id: 77, cat: 'hist', topic: 'Plato',                   q: 'Plato (what is his view?): knowledge only of forms, or also of concrete things?', opts: ['Knowledge only of forms', 'Knowledge also of concrete things'],
    detail: "Interpreting Plato:\n\n• Knowledge only of forms: we can know only the eternal Forms, with the changing physical world yielding mere opinion.\n• Knowledge also of concrete things: knowledge of concrete things is also possible." },
  { id: 78, cat: 'pol',  topic: 'Politics',                q: 'Politics: capitalism or socialism?',               opts: ['Capitalism', 'Socialism'],
    detail: "Broadly, which economic system do you favor?\n\n• Capitalism: private ownership and markets.\n• Socialism: collective or social ownership, with planning or strong redistribution." },
  { id: 79, cat: 'meta', topic: 'Possible worlds',         q: 'Possible worlds: abstract, concrete, or nonexistent?', opts: ['Abstract', 'Concrete', 'Nonexistent'],
    detail: "Talk of 'possible worlds' helps analyze necessity and possibility — but what are they?\n\n• Abstract: abstract objects, like maximal sets of propositions.\n• Concrete: real, spatiotemporally separate universes, every bit as real as ours (Lewis's modal realism).\n• Nonexistent: just a useful manner of speaking." },
  { id: 80, cat: 'meta', topic: 'Sufficient reason',       q: 'Principle of sufficient reason: true or false?',  opts: ['True', 'False'],
    detail: "The principle of sufficient reason holds that everything that is the case has an explanation — there are no brute, inexplicable facts.\n\nIt is powerful in rationalist metaphysics (Leibniz), but seems to lead to surprising conclusions. True or false?" },
  { id: 81, cat: 'meta', topic: 'Properties',              q: 'Properties: classes, immanent universals, transcendent universals, tropes, or nonexistent?', opts: ['Classes', 'Immanent universals', 'Transcendent universals', 'Tropes', 'Nonexistent'],
    optNotes: ['just the set of red things', 'one entity in each red thing (Aristotle)', 'exist apart from their instances (Plato)', 'particular instances: this red here', 'there are no properties'],
    detail: "What are properties such as 'redness'?" },
  { id: 82, cat: 'ethm', topic: 'Practical reason',        q: 'Practical reason: Aristotelian, Humean, or Kantian?', opts: ['Aristotelian', 'Humean', 'Kantian'],
    detail: "What governs reasoning about what to do?\n\n• Aristotelian: practical reason aims at the good life and is cultivated through virtue.\n• Humean: reason is the slave of the passions — it serves desires you already have.\n• Kantian: reason itself can set ends and bind us through rational principles." },
  { id: 83, cat: 'mind', topic: 'Propositional attitudes', q: 'Propositional attitudes: dispositional, phenomenal, representational, or nonexistent?', opts: ['Dispositional', 'Phenomenal', 'Representational', 'Nonexistent'],
    optNotes: ['a disposition to behave in certain ways', 'grounded in conscious experience', 'an inner representation with content', 'folk psychology; may pick out nothing real'],
    detail: "What is it to believe or desire something?" },
  { id: 84, cat: 'lang', topic: 'Propositions',            q: 'Propositions: sets, structured entities, simple entities, acts, or nonexistent?', opts: ['Sets', 'Structured entities', 'Simple entities', 'Acts', 'Nonexistent'],
    optNotes: ['e.g. sets of possible worlds', 'built from constituents', 'simple, unstructured entities', 'acts of predication', 'a posit we can do without'],
    detail: "Propositions are meant to be what sentences express and what beliefs are about — but what are they?" },
  { id: 85, cat: 'sci',  topic: 'Quantum mechanics',       q: 'Quantum mechanics: collapse, hidden-variables, many-worlds, or epistemic?', opts: ['Collapse', 'Hidden-variables', 'Many-worlds', 'Epistemic'],
    optNotes: ['measurement collapses the wavefunction', "determinate values we don't see (Bohm)", 'every outcome happens, in branches (Everett)', 'the wavefunction is our information'],
    detail: "How should we interpret quantum mechanics?" },
  { id: 86, cat: 'pol',  topic: 'Race categories',         q: 'Race categories: preserve, revise, or eliminate?', opts: ['Preserve', 'Revise', 'Eliminate'],
    detail: "Going forward, what should we do with our racial categories?\n\n• Preserve: keep them as they are.\n• Revise: reform them.\n• Eliminate: abandon racial classification altogether." },
  { id: 87, cat: 'epis', topic: 'Skepticism response',     q: 'Response to external-world skepticism (strongest?): abductive, contextualist, dogmatist, epistemic externalist, semantic externalist, or pragmatic?', opts: ['Abductive', 'Contextualist', 'Dogmatist', 'Epistemic externalist', 'Semantic externalist', 'Pragmatic'],
    optNotes: ['realism best explains experience', 'the standards shift', 'perception gives immediate justification', 'reliably formed belief suffices', "the thought 'I'm a brain in a vat' can't be true", 'the doubt is idle'],
    detail: "What's the best reply to the skeptic who says you can't know you're not dreaming or a brain in a vat?" },
  { id: 88, cat: 'epis', topic: 'Rational disagreement',   q: 'Rational disagreement (same evidence): uniqueness or permissiveness?', opts: ['Uniqueness', 'Permissiveness'],
    detail: "Given one body of evidence, how many rational responses are there?\n\n• Uniqueness: exactly one rational attitude to take toward a question.\n• Permissiveness: equally rational people can respond to the same evidence with different beliefs." },
  { id: 89, cat: 'lang', topic: 'Semantic content',        q: 'Semantic content (how context-dependent?): minimalism, moderate contextualism, or radical contextualism?', opts: ['Minimalism', 'Moderate contextualism', 'Radical contextualism'],
    detail: "How much does context shape what a sentence says?\n\n• Minimalism: very little — sentences have stable, context-light contents.\n• Moderate contextualism: context fills in a fair amount.\n• Radical contextualism: context pervades meaning, so the words alone fix almost nothing." },
  { id: 90, cat: 'lang', topic: 'Sleeping beauty',         q: 'Sleeping beauty (credence in heads on waking?): one-third or one-half?', opts: ['One-third', 'One-half'],
    detail: "Beauty is put to sleep and a fair coin is tossed. On heads she's woken once; on tails, twice (with her memory wiped between). Each time she wakes, what credence should she give to heads?\n\n• One-half: 'halfers' say 1/2 — the coin was fair.\n• One-third: 'thirders' say 1/3 — a waking is more likely under tails." },
  { id: 91, cat: 'sci',  topic: 'Spacetime',               q: 'Spacetime: relationism or substantivalism?',      opts: ['Relationism', 'Substantivalism'],
    detail: "What is spacetime?\n\n• Substantivalism: a real entity in its own right — a container that could exist even if empty (Newton).\n• Relationism: nothing over and above the spatial and temporal relations between things (Leibniz)." },
  { id: 92, cat: 'meta', topic: 'Statue and lump',         q: 'Statue and lump: one thing or two things?',       opts: ['One thing', 'Two things'],
    detail: "A clay statue and the lump of clay it's made of seem to share every atom — yet squashing it destroys the statue while the lump survives.\n\n• Two things: they differ, making them two coincident objects.\n• One thing: they're really one and the same thing." },
  { id: 93, cat: 'meta', topic: 'Temporal ontology',       q: 'Temporal ontology: presentism, eternalism, or growing block?', opts: ['Presentism', 'Eternalism', 'Growing block'],
    detail: "Which times exist?\n\n• Presentism: only the present moment is real.\n• Eternalism: past, present, and future are all equally real (the 'block universe').\n• Growing block: the past and present are real and the universe grows as time passes, but the future is not yet real." },
  { id: 94, cat: 'lang', topic: 'Theory of reference',     q: 'Theory of reference: causal, descriptive, or deflationary?', opts: ['Causal', 'Descriptive', 'Deflationary'],
    detail: "How do words hook onto things?\n\n• Causal: reference is fixed by an initial 'baptism' and a causal chain of use down to us (Kripke).\n• Descriptive: a name refers to whatever fits the descriptions we associate with it.\n• Deflationary: there is no deep theory of reference to be given." },
  { id: 95, cat: 'meta', topic: 'Time travel',             q: 'Time travel: metaphysically possible or impossible?', opts: ['Metaphysically possible', 'Metaphysically impossible'],
    detail: "Is travel into the past metaphysically possible — coherent in principle, setting aside whether it's technologically feasible?\n\nWorries include the grandfather paradox: could you go back and prevent your own birth?" },
  { id: 96, cat: 'lang', topic: 'True contradictions',     q: 'True contradictions: impossible, possible but non-actual, or actual?', opts: ['Impossible', 'Possible but non-actual', 'Actual'],
    detail: "Could a contradiction ('p and not-p') ever be true? Classical logic says never; dialetheists argue some actually are true — the liar paradox being the stock example.\n\n• Impossible: never true.\n• Possible but non-actual: possible, but never actually true.\n• Actual: actually true in some cases." },
  { id: 97, cat: 'sci',  topic: 'Units of selection',      q: 'Units of natural selection: genes or organisms?',  opts: ['Genes', 'Organisms'],
    detail: "What does natural selection primarily act on?\n\n• Genes: 'selfish' genes competing to propagate themselves (Dawkins).\n• Organisms: whole organisms surviving and reproducing.\n\n(Some would add groups to the list.)" },
  { id: 98, cat: 'sci',  topic: 'Values in science',       q: 'Values in science (is ideal reasoning sensitive to non-epistemic values?): necessarily value-free, necessarily value-laden, or can be either?', opts: ['Necessarily value-free', 'Necessarily value-laden', 'Can be either'],
    detail: "Can ideal scientific reasoning be free of non-epistemic values — moral, political, social?\n\n• Necessarily value-free: the ideal excludes them.\n• Necessarily value-laden: they unavoidably enter, for instance in setting how much evidence is enough.\n• Can be either: it depends on the case." },
  { id: 99, cat: 'appl', topic: 'Well-being',              q: 'Well-being: hedonism, desire satisfaction, or objective list?', opts: ['Hedonism', 'Desire satisfaction', 'Objective list'],
    detail: "What makes a life go well for the person living it?\n\n• Hedonism: pleasure and the absence of pain.\n• Desire satisfaction: getting what you want.\n• Objective list: certain goods — knowledge, friendship, achievement — benefit you whether or not you happen to want them." },
  { id: 100, cat: 'hist', topic: 'Wittgenstein',           q: 'Wittgenstein (which do you prefer?): early or late?', opts: ['Early', 'Late'],
    detail: "Two phases of Wittgenstein.\n\n• Early (the Tractatus): language pictures the world, with a precise underlying logical structure.\n• Late (the Philosophical Investigations): meaning is use within social 'language-games', repudiating much of the early view.\n\nWhich do you find more compelling?" }
];
