/* ------------------------------------------------------------------ *
 *  The 100 questions of the 2020 PhilPapers Survey, turned into a
 *  personality test.  Source question wording follows the published
 *  survey design (Bourget & Chalmers, "Philosophers on Philosophy:
 *  The 2020 PhilPapers Survey").
 *
 *  Each question is assigned to one of ten thematic categories so the
 *  results can be drawn as a colour-banded profile diagram (see the
 *  example SVG in /example).
 * ------------------------------------------------------------------ */

/* Category metadata — colours echo the soft, banded palette of the
 * example diagram (rounded cards, pale fill, saturated accent). */
window.PPT_CATEGORIES = [
  { key: 'meta', name: 'Metaphysics & religion',        fill: '#EEEDFE', stroke: '#534AB7', title: '#3C3489', text: '#534AB7' },
  { key: 'mind', name: 'Mind & cognition',              fill: '#E1F5EE', stroke: '#0F6E56', title: '#085041', text: '#0F6E56' },
  { key: 'consc', name: 'Consciousness, self & AI',     fill: '#E0F2F4', stroke: '#0E7490', title: '#0B5566', text: '#0E7490' },
  { key: 'epis', name: 'Epistemology',                  fill: '#E6F1FB', stroke: '#185FA5', title: '#0C447C', text: '#185FA5' },
  { key: 'ethm', name: 'Ethics & meta-ethics',          fill: '#FAECE7', stroke: '#993C1D', title: '#712B13', text: '#993C1D' },
  { key: 'appl', name: 'Applied ethics & the good life', fill: '#FBE9EF', stroke: '#A12B53', title: '#781E3D', text: '#A12B53' },
  { key: 'pol',  name: 'Politics, society & identity',  fill: '#FAEEDA', stroke: '#854F0B', title: '#633806', text: '#854F0B' },
  { key: 'lang', name: 'Language, logic & mathematics',  fill: '#F3E9FB', stroke: '#6B2FA1', title: '#4E2178', text: '#6B2FA1' },
  { key: 'sci',  name: 'Science & nature',              fill: '#EAF3E2', stroke: '#4D7C0F', title: '#3A5E0B', text: '#4D7C0F' },
  { key: 'hist', name: 'History & methods',             fill: '#EEEEEC', stroke: '#57534E', title: '#3D3D3A', text: '#57534E' }
];

/* The questions.  `id` matches the survey numbering above; `cat` is the
 * category key; `topic` is the short label used on result cards; `q` is
 * the full prompt; `opts` are the answer options; `multi:true` marks the
 * two questions that allow multiple answers. */
window.PPT_QUESTIONS = [
  { id: 1,  cat: 'epis', topic: 'A priori knowledge',      q: 'A priori knowledge: is there any?',               opts: ['Yes', 'No'] },
  { id: 2,  cat: 'lang', topic: 'Abstract objects',        q: 'Abstract objects: Platonism or nominalism?',      opts: ['Platonism', 'Nominalism'] },
  { id: 3,  cat: 'appl', topic: 'Aesthetic value',         q: 'Aesthetic value: objective or subjective?',       opts: ['Objective', 'Subjective'] },
  { id: 4,  cat: 'epis', topic: 'Analytic–synthetic',      q: 'Analytic–synthetic distinction: is there one?',   opts: ['Yes', 'No'] },
  { id: 5,  cat: 'epis', topic: 'Epistemic justification', q: 'Epistemic justification: internalism or externalism?', opts: ['Internalism', 'Externalism'] },
  { id: 6,  cat: 'epis', topic: 'External world',          q: 'External world: idealism, skepticism, or non-skeptical realism?', opts: ['Idealism', 'Skepticism', 'Non-skeptical realism'] },
  { id: 7,  cat: 'meta', topic: 'Free will',               q: 'Free will: compatibilism, libertarianism, or no free will?', opts: ['Compatibilism', 'Libertarianism', 'No free will'] },
  { id: 8,  cat: 'meta', topic: 'God',                     q: 'God: theism or atheism?',                         opts: ['Theism', 'Atheism'] },
  { id: 9,  cat: 'epis', topic: 'Knowledge',               q: 'Knowledge: empiricism or rationalism?',           opts: ['Empiricism', 'Rationalism'] },
  { id: 10, cat: 'epis', topic: 'Knowledge claims',        q: 'Knowledge claims: contextualism, relativism, or invariantism?', opts: ['Contextualism', 'Relativism', 'Invariantism'] },
  { id: 11, cat: 'sci',  topic: 'Laws of nature',          q: 'Laws of nature: Humean or non-Humean?',           opts: ['Humean', 'Non-Humean'] },
  { id: 12, cat: 'lang', topic: 'Logic',                   q: 'Logic: classical or non-classical?',              opts: ['Classical', 'Non-classical'] },
  { id: 13, cat: 'mind', topic: 'Mental content',          q: 'Mental content: internalism or externalism?',     opts: ['Internalism', 'Externalism'] },
  { id: 14, cat: 'ethm', topic: 'Meta-ethics',             q: 'Meta-ethics: moral realism or moral anti-realism?', opts: ['Moral realism', 'Moral anti-realism'] },
  { id: 15, cat: 'hist', topic: 'Metaphilosophy',          q: 'Metaphilosophy: naturalism or non-naturalism?',   opts: ['Naturalism', 'Non-naturalism'] },
  { id: 16, cat: 'mind', topic: 'Mind',                    q: 'Mind: physicalism or non-physicalism?',           opts: ['Physicalism', 'Non-physicalism'] },
  { id: 17, cat: 'ethm', topic: 'Moral judgment',          q: 'Moral judgment: cognitivism or non-cognitivism?', opts: ['Cognitivism', 'Non-cognitivism'] },
  { id: 18, cat: 'ethm', topic: 'Moral motivation',        q: 'Moral motivation: internalism or externalism?',   opts: ['Internalism', 'Externalism'] },
  { id: 19, cat: 'lang', topic: "Newcomb's problem",       q: "Newcomb's problem: one box or two boxes?",        opts: ['One box', 'Two boxes'] },
  { id: 20, cat: 'ethm', topic: 'Normative ethics',        q: 'Normative ethics: deontology, consequentialism, or virtue ethics?', opts: ['Deontology', 'Consequentialism', 'Virtue ethics'] },
  { id: 21, cat: 'mind', topic: 'Perceptual experience',   q: 'Perceptual experience: disjunctivism, qualia theory, representationalism, or sense-datum theory?', opts: ['Disjunctivism', 'Qualia theory', 'Representationalism', 'Sense-datum theory'] },
  { id: 22, cat: 'consc', topic: 'Personal identity',      q: 'Personal identity: biological, psychological, or further-fact view?', opts: ['Biological view', 'Psychological view', 'Further-fact view'] },
  { id: 23, cat: 'pol',  topic: 'Political philosophy',    q: 'Political philosophy: communitarianism, egalitarianism, or libertarianism?', opts: ['Communitarianism', 'Egalitarianism', 'Libertarianism'] },
  { id: 24, cat: 'lang', topic: 'Proper names',            q: 'Proper names: Fregean or Millian?',               opts: ['Fregean', 'Millian'] },
  { id: 25, cat: 'sci',  topic: 'Science',                 q: 'Science: scientific realism or scientific anti-realism?', opts: ['Scientific realism', 'Scientific anti-realism'] },
  { id: 26, cat: 'consc', topic: 'Teletransporter',        q: 'Teletransporter (new matter): survival or death?', opts: ['Survival', 'Death'] },
  { id: 27, cat: 'meta', topic: 'Time',                    q: 'Time: A-theory or B-theory?',                     opts: ['A-theory', 'B-theory'] },
  { id: 28, cat: 'appl', topic: 'Trolley problem',         q: 'Trolley problem (five ahead, one on a side track, turning requires switching): switch or don’t switch?', opts: ['Switch', "Don't switch"] },
  { id: 29, cat: 'lang', topic: 'Truth',                   q: 'Truth: correspondence, deflationary, or epistemic?', opts: ['Correspondence', 'Deflationary', 'Epistemic'] },
  { id: 30, cat: 'consc', topic: 'Zombies',                q: 'Zombies: inconceivable, conceivable but not metaphysically possible, or metaphysically possible?', opts: ['Inconceivable', 'Conceivable but not metaphysically possible', 'Metaphysically possible'] },
  { id: 31, cat: 'hist', topic: 'Aim of philosophy',       q: 'Aim of philosophy (most important?): truth/knowledge, understanding, wisdom, happiness, or goodness/justice?', opts: ['Truth/knowledge', 'Understanding', 'Wisdom', 'Happiness', 'Goodness/justice'] },
  { id: 32, cat: 'appl', topic: 'Eating animals',          q: 'Eating animals and animal products (ordinarily permissible?): omnivorism, vegetarianism, or veganism?', opts: ['Omnivorism (yes and yes)', 'Vegetarianism (no and yes)', 'Veganism (no and no)'] },
  { id: 33, cat: 'appl', topic: 'Experience machine',      q: 'Experience machine: would you enter?',             opts: ['Yes', 'No'] },
  { id: 34, cat: 'appl', topic: 'Footbridge',              q: 'Footbridge (pushing a man off a bridge will save five below): push or don’t push?', opts: ['Push', "Don't push"] },
  { id: 35, cat: 'pol',  topic: 'Gender',                  q: 'Gender: biological, psychological, social, or unreal?', opts: ['Biological', 'Psychological', 'Social', 'Unreal'] },
  { id: 36, cat: 'appl', topic: 'Meaning of life',         q: 'Meaning of life: subjective, objective, or nonexistent?', opts: ['Subjective', 'Objective', 'Nonexistent'] },
  { id: 37, cat: 'hist', topic: 'Philosophical method',    q: 'Philosophical method (most useful?): conceptual analysis, conceptual engineering, empirical, experimental, formal, intuition-based, or linguistic?', opts: ['Conceptual analysis', 'Conceptual engineering', 'Empirical philosophy', 'Experimental philosophy', 'Formal philosophy', 'Intuition-based philosophy', 'Linguistic philosophy'], multi: true },
  { id: 38, cat: 'hist', topic: 'Philosophical progress',  q: 'Philosophical progress (how much is there?): none, a little, or a lot?', opts: ['None', 'A little', 'A lot'] },
  { id: 39, cat: 'pol',  topic: 'Race',                    q: 'Race: biological, social, or unreal?',             opts: ['Biological', 'Social', 'Unreal'] },
  { id: 40, cat: 'lang', topic: 'Vagueness',               q: 'Vagueness: epistemic, metaphysical, or semantic?', opts: ['Epistemic', 'Metaphysical', 'Semantic'] },
  { id: 41, cat: 'appl', topic: 'Abortion',                q: 'Abortion (first trimester, no special circumstances): permissible or impermissible?', opts: ['Permissible', 'Impermissible'] },
  { id: 42, cat: 'appl', topic: 'Aesthetic experience',    q: 'Aesthetic experience: perception, pleasure, or sui generis?', opts: ['Perception', 'Pleasure', 'Sui generis'] },
  { id: 43, cat: 'epis', topic: 'Analysis of knowledge',   q: 'Analysis of knowledge: justified true belief, other analysis, or no analysis?', opts: ['Justified true belief', 'Other analysis', 'No analysis'] },
  { id: 44, cat: 'meta', topic: 'Arguments for theism',    q: 'Arguments for theism (strongest?): cosmological, design, ontological, pragmatic, or moral?', opts: ['Cosmological', 'Design', 'Ontological', 'Pragmatic', 'Moral'] },
  { id: 45, cat: 'epis', topic: 'Belief or credence',      q: 'Belief or credence (more fundamental?): belief, credence, or neither?', opts: ['Belief', 'Credence', 'Neither'] },
  { id: 46, cat: 'appl', topic: 'Capital punishment',      q: 'Capital punishment: permissible or impermissible?', opts: ['Permissible', 'Impermissible'] },
  { id: 47, cat: 'meta', topic: 'Causation',               q: 'Causation: counterfactual/difference-making, process/production, primitive, or nonexistent?', opts: ['Counterfactual / difference-making', 'Process / production', 'Primitive', 'Nonexistent'] },
  { id: 48, cat: 'consc', topic: 'Chinese room',           q: 'Chinese room: does the system understand?',        opts: ['Understands', "Doesn't understand"] },
  { id: 49, cat: 'mind', topic: 'Concepts',                q: 'Concepts: nativism or empiricism?',                opts: ['Nativism', 'Empiricism'] },
  { id: 50, cat: 'consc', topic: 'Consciousness',          q: 'Consciousness: dualism, eliminativism, functionalism, identity theory, or panpsychism?', opts: ['Dualism', 'Eliminativism', 'Functionalism', 'Identity theory', 'Panpsychism'] },
  { id: 51, cat: 'lang', topic: 'Continuum hypothesis',    q: 'Continuum hypothesis (determinate truth-value?): determinate or indeterminate?', opts: ['Determinate', 'Indeterminate'] },
  { id: 52, cat: 'meta', topic: 'Cosmological fine-tuning', q: 'Cosmological fine-tuning (what explains it?): design, multiverse, brute fact, or no fine-tuning?', opts: ['Design', 'Multiverse', 'Brute fact', 'No fine-tuning'] },
  { id: 53, cat: 'appl', topic: 'Environmental ethics',    q: 'Environmental ethics: anthropocentric or non-anthropocentric?', opts: ['Anthropocentric', 'Non-anthropocentric'] },
  { id: 54, cat: 'epis', topic: 'Justification (theory)',  q: 'Epistemic justification: coherentism, infinitism, nonreliabilist foundationalism, or reliabilism?', opts: ['Coherentism', 'Infinitism', 'Nonreliabilist foundationalism', 'Reliabilism'] },
  { id: 55, cat: 'mind', topic: 'Extended mind',           q: 'Extended mind: yes or no?',                        opts: ['Yes', 'No'] },
  { id: 56, cat: 'lang', topic: 'Foundations of maths',    q: 'Foundations of mathematics: intuitionism/constructivism, formalism, logicism, structuralism, or set-theoretic?', opts: ['Intuitionism / constructivism', 'Formalism', 'Logicism', 'Structuralism', 'Set-theoretic'] },
  { id: 57, cat: 'pol',  topic: 'Gender categories',       q: 'Gender categories: preserve, revise, or eliminate?', opts: ['Preserve', 'Revise', 'Eliminate'] },
  { id: 58, cat: 'mind', topic: 'Grounds of intentionality', q: 'Grounds of intentionality: causal/teleological, inferential, interpretational, phenomenal, or primitive?', opts: ['Causal / teleological', 'Inferential', 'Interpretational', 'Phenomenal', 'Primitive'] },
  { id: 59, cat: 'consc', topic: 'Hard problem',           q: 'Hard problem of consciousness: is there one?',     opts: ['Yes', 'No'] },
  { id: 60, cat: 'appl', topic: 'Genetic engineering',     q: 'Human genetic engineering: permissible or impermissible?', opts: ['Permissible', 'Impermissible'] },
  { id: 61, cat: 'hist', topic: 'Hume',                    q: 'Hume (what is his view?): skeptic or naturalist?', opts: ['Skeptic', 'Naturalist'] },
  { id: 62, cat: 'appl', topic: 'Immortality',             q: 'Immortality: would you choose it?',                opts: ['Yes', 'No'] },
  { id: 63, cat: 'meta', topic: 'Interlevel metaphysics',  q: 'Interlevel metaphysics (most useful?): grounding, identity, realization, or supervenience?', opts: ['Grounding', 'Identity', 'Realization', 'Supervenience'] },
  { id: 64, cat: 'hist', topic: 'Kant',                    q: 'Kant (what is his view?): one world or two worlds?', opts: ['One world', 'Two worlds'] },
  { id: 65, cat: 'pol',  topic: 'Law',                     q: 'Law: legal positivism or legal non-positivism?',  opts: ['Legal positivism', 'Legal non-positivism'] },
  { id: 66, cat: 'meta', topic: 'Material composition',    q: 'Material composition: nihilism, restrictivism, or universalism?', opts: ['Nihilism', 'Restrictivism', 'Universalism'] },
  { id: 67, cat: 'meta', topic: 'Metaontology',            q: 'Metaontology: heavyweight realism, deflationary realism, or anti-realism?', opts: ['Heavyweight realism', 'Deflationary realism', 'Anti-realism'] },
  { id: 68, cat: 'hist', topic: 'History of philosophy',   q: 'Method in the history of philosophy: analytic/rational reconstruction or contextual/historicist?', opts: ['Analytic / rational reconstruction', 'Contextual / historicist'] },
  { id: 69, cat: 'pol',  topic: 'Political method',        q: 'Method in political philosophy: ideal theory or non-ideal theory?', opts: ['Ideal theory', 'Non-ideal theory'] },
  { id: 70, cat: 'consc', topic: 'Mind uploading',         q: 'Mind uploading (brain replaced by digital emulation): survival or death?', opts: ['Survival', 'Death'] },
  { id: 71, cat: 'ethm', topic: 'Moral principles',        q: 'Moral principles: moral generalism or moral particularism?', opts: ['Moral generalism', 'Moral particularism'] },
  { id: 72, cat: 'ethm', topic: 'Morality (nature of)',    q: 'Morality: non-naturalism, naturalist realism, constructivism, expressivism, or error theory?', opts: ['Non-naturalism', 'Naturalist realism', 'Constructivism', 'Expressivism', 'Error theory'] },
  { id: 73, cat: 'ethm', topic: 'Normative concepts',      q: 'Normative concepts (most fundamental?): fit, ought, reason, or value?', opts: ['Fit', 'Ought', 'Reason', 'Value'] },
  { id: 74, cat: 'consc', topic: 'Other minds',            q: 'Other minds (which groups have conscious members?): adult humans, cats, fish, flies, worms, plants, particles, newborns, current AI, future AI?', opts: ['Adult humans', 'Cats', 'Fish', 'Flies', 'Worms', 'Plants', 'Particles', 'Newborn babies', 'Current AI systems', 'Future AI systems'], multi: true },
  { id: 75, cat: 'ethm', topic: 'Ought implies can',       q: 'Ought implies can: yes or no?',                    opts: ['Yes', 'No'] },
  { id: 76, cat: 'hist', topic: 'Philosophical knowledge', q: 'Philosophical knowledge (how much is there?): none, a little, or a lot?', opts: ['None', 'A little', 'A lot'] },
  { id: 77, cat: 'hist', topic: 'Plato',                   q: 'Plato (what is his view?): knowledge only of forms, or also of concrete things?', opts: ['Knowledge only of forms', 'Knowledge also of concrete things'] },
  { id: 78, cat: 'pol',  topic: 'Politics',                q: 'Politics: capitalism or socialism?',               opts: ['Capitalism', 'Socialism'] },
  { id: 79, cat: 'meta', topic: 'Possible worlds',         q: 'Possible worlds: abstract, concrete, or nonexistent?', opts: ['Abstract', 'Concrete', 'Nonexistent'] },
  { id: 80, cat: 'meta', topic: 'Sufficient reason',       q: 'Principle of sufficient reason: true or false?',  opts: ['True', 'False'] },
  { id: 81, cat: 'meta', topic: 'Properties',              q: 'Properties: classes, immanent universals, transcendent universals, tropes, or nonexistent?', opts: ['Classes', 'Immanent universals', 'Transcendent universals', 'Tropes', 'Nonexistent'] },
  { id: 82, cat: 'ethm', topic: 'Practical reason',        q: 'Practical reason: Aristotelian, Humean, or Kantian?', opts: ['Aristotelian', 'Humean', 'Kantian'] },
  { id: 83, cat: 'mind', topic: 'Propositional attitudes', q: 'Propositional attitudes: dispositional, phenomenal, representational, or nonexistent?', opts: ['Dispositional', 'Phenomenal', 'Representational', 'Nonexistent'] },
  { id: 84, cat: 'lang', topic: 'Propositions',            q: 'Propositions: sets, structured entities, simple entities, acts, or nonexistent?', opts: ['Sets', 'Structured entities', 'Simple entities', 'Acts', 'Nonexistent'] },
  { id: 85, cat: 'sci',  topic: 'Quantum mechanics',       q: 'Quantum mechanics: collapse, hidden-variables, many-worlds, or epistemic?', opts: ['Collapse', 'Hidden-variables', 'Many-worlds', 'Epistemic'] },
  { id: 86, cat: 'pol',  topic: 'Race categories',         q: 'Race categories: preserve, revise, or eliminate?', opts: ['Preserve', 'Revise', 'Eliminate'] },
  { id: 87, cat: 'epis', topic: 'Skepticism response',     q: 'Response to external-world skepticism (strongest?): abductive, contextualist, dogmatist, epistemic externalist, semantic externalist, or pragmatic?', opts: ['Abductive', 'Contextualist', 'Dogmatist', 'Epistemic externalist', 'Semantic externalist', 'Pragmatic'] },
  { id: 88, cat: 'epis', topic: 'Rational disagreement',   q: 'Rational disagreement (same evidence): uniqueness or permissiveness?', opts: ['Uniqueness', 'Permissiveness'] },
  { id: 89, cat: 'lang', topic: 'Semantic content',        q: 'Semantic content (how context-dependent?): minimalism, moderate contextualism, or radical contextualism?', opts: ['Minimalism', 'Moderate contextualism', 'Radical contextualism'] },
  { id: 90, cat: 'lang', topic: 'Sleeping beauty',         q: 'Sleeping beauty (credence in heads on waking?): one-third or one-half?', opts: ['One-third', 'One-half'] },
  { id: 91, cat: 'sci',  topic: 'Spacetime',               q: 'Spacetime: relationism or substantivalism?',      opts: ['Relationism', 'Substantivalism'] },
  { id: 92, cat: 'meta', topic: 'Statue and lump',         q: 'Statue and lump: one thing or two things?',       opts: ['One thing', 'Two things'] },
  { id: 93, cat: 'meta', topic: 'Temporal ontology',       q: 'Temporal ontology: presentism, eternalism, or growing block?', opts: ['Presentism', 'Eternalism', 'Growing block'] },
  { id: 94, cat: 'lang', topic: 'Theory of reference',     q: 'Theory of reference: causal, descriptive, or deflationary?', opts: ['Causal', 'Descriptive', 'Deflationary'] },
  { id: 95, cat: 'meta', topic: 'Time travel',             q: 'Time travel: metaphysically possible or impossible?', opts: ['Metaphysically possible', 'Metaphysically impossible'] },
  { id: 96, cat: 'lang', topic: 'True contradictions',     q: 'True contradictions: impossible, possible but non-actual, or actual?', opts: ['Impossible', 'Possible but non-actual', 'Actual'] },
  { id: 97, cat: 'sci',  topic: 'Units of selection',      q: 'Units of natural selection: genes or organisms?',  opts: ['Genes', 'Organisms'] },
  { id: 98, cat: 'sci',  topic: 'Values in science',       q: 'Values in science (is ideal reasoning sensitive to non-epistemic values?): necessarily value-free, necessarily value-laden, or can be either?', opts: ['Necessarily value-free', 'Necessarily value-laden', 'Can be either'] },
  { id: 99, cat: 'appl', topic: 'Well-being',              q: 'Well-being: hedonism, desire satisfaction, or objective list?', opts: ['Hedonism', 'Desire satisfaction', 'Objective list'] },
  { id: 100, cat: 'hist', topic: 'Wittgenstein',           q: 'Wittgenstein (which do you prefer?): early or late?', opts: ['Early', 'Late'] }
];
